# Generated by Django 3.2.18 on 2023-03-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegedible', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
